// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4yBxZeS0G1RzUtnAy1HbXdU0JgS1dLa0',
    appId: '1:15697676186:web:99058d00b6ced2949c1c23',
    messagingSenderId: '15697676186',
    projectId: 'areuwfo-tracker',
    authDomain: 'areuwfo-tracker.firebaseapp.com',
    storageBucket: 'areuwfo-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_m_PMFd21jpmuFIYNfHsdLY11gBtDEvs',
    appId: '1:15697676186:android:a9d018e500beb4fd9c1c23',
    messagingSenderId: '15697676186',
    projectId: 'areuwfo-tracker',
    storageBucket: 'areuwfo-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7BRNiLVUlatDB9OlY2gj3GB0Cfj1fB_4',
    appId: '1:15697676186:ios:f48a677294008e0e9c1c23',
    messagingSenderId: '15697676186',
    projectId: 'areuwfo-tracker',
    storageBucket: 'areuwfo-tracker.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7BRNiLVUlatDB9OlY2gj3GB0Cfj1fB_4',
    appId: '1:15697676186:ios:f48a677294008e0e9c1c23',
    messagingSenderId: '15697676186',
    projectId: 'areuwfo-tracker',
    storageBucket: 'areuwfo-tracker.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4yBxZeS0G1RzUtnAy1HbXdU0JgS1dLa0',
    appId: '1:15697676186:web:a858818fc325ad7a9c1c23',
    messagingSenderId: '15697676186',
    projectId: 'areuwfo-tracker',
    authDomain: 'areuwfo-tracker.firebaseapp.com',
    storageBucket: 'areuwfo-tracker.firebasestorage.app',
  );
}
